---
  - hosts: apache_server_2
    become: yes
    tasks:
      - name: Copy MOTD into place
        copy:
          dest: /var/www/html
          src: /Users/jonathandiaz/documents/aws/ansible/ansible-interview-demo/index.html
      - name: Copy CSS
        copy:
          dest: /var/www/html
          src: /Users/jonathandiaz/documents/aws/ansible/ansible-interview-demo/style.css      