---
  - hosts: apache_server
    become: yes
    tasks:
      - name: Copy html file
        copy:
          dest: /var/www/html
          src: /var/lib/jenkins/workspace/Invoke_Ansible_Playbook/index.html
      - name: Copy CSS file
        copy:
          dest: /var/www/html
          src: /var/lib/jenkins/workspace/Invoke_Ansible_Playbook/style.css    